name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        gcc_version: [10, 11, 12]
        build_type: [Release, Debug]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.version }}
          platform: x8=64

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target task

      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target test

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ./test
