name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        gcc_version: [10, 11, 12]
        build_type: [Release, Debug]

    runs-on: ubuntu-22.04

    env:
      CC: gcc-${{ matrix.gcc_version }}
      CXX: g++-${{ matrix.gcc_version }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target task

      - name: Run with test input
        working-directory: ${{github.workspace}}/build
        run: ./task ${{github.workspace}}/input.txt

      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target test

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ./test

  clang:
    strategy:
      fail-fast: false
      matrix:
        gcc_version: [ 12, 13, 14 ]
        build_type: [ Release, Debug ]

    runs-on: ubuntu-22.04

    env:
      CC: clang-${{ matrix.clang_version }}
      CXX: clang-${{ matrix.clang_version }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target task

      - name: Run with test input
        working-directory: ${{github.workspace}}/build
        run: ./task ${{github.workspace}}/input.txt

      - name: Build Tests
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --target test

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        run: ./test
